name: MacOS
on: 
  push:
    paths:
      - '*.pro'
      - 'src/**'
      - '.github/workflows/macos.yml'
  pull_request:
    paths:
      - '*.pro'
      - 'src/**'
      - '.github/workflows/macos.yml' 
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11.0]
        qt_ver: [5.9.9]
        qt_arch: [clang_64]
    env:
      targetName: WifiMouseServer
    steps:
      # macos 11.0 默认环境变了,要指定
      - name: prepare env
        if: ${{ matrix.os == 'macos-11.0' }}
        run: |
          softwareupdate --all --install --force
          sudo xcode-select --print-path
          sudo xcode-select --switch /Library/Developer/CommandLineTools       
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_ver }}
          cached: 'false'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: build macos
        run: |
          qmake
          make
      - uses: actions/upload-artifact@v3
        with:
            name: my-artifact
            path: Users/runner/work/WifiMouseServer/WifiMouseServer
